version: '3.5'

services:
  wordpress:
    build:
      context: ../../..
      dockerfile: Dockerfile
    volumes:
      - ../../../wp-content:/var/www/wp-content:delegated
    ports:
      - "8080:80"
    environment:
      IS_DOCKER: "true"
      FS_METHOD: direct
