version: '3.5'

services:
  redis:
    image: redis:5.0.4-alpine
    volumes:
      - redis_data:/var/lib/redis:delegated
    ports:
      - "6380:6379"
    logging:
      driver: none

  wordpress_db:
    image: mariadb:10.4
    volumes:
      - ./data/wordpress:/docker-entrypoint-initdb.d:ro
      - db-data:/var/lib/mysql:delegated
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    logging:
      driver: none

  wordpress:
    build:
      context: ../../..
      dockerfile: Dockerfile
    depends_on:
      - redis
      - wordpress_db
    volumes:
      - ../../../wordpress:/var/www/wordpress:cached
      - ../../../wp-content:/var/www/wp-content:cached
    ports:
      - "8080:80"
    environment:
      IS_DOCKER: "true"
      DB_HOST: wordpress_db
      DB_PASSWORD: wordpress
      DB_NAME: wordpress
      DB_USER: wordpress
      WORDPRESS_SITE_URL: http://www.dev.secretparty.io:8080
      FS_METHOD: direct
      WP_REDIS_HOST: redis
      WP_REDIS_DATABASE: 4
      # For debugging only:
      WP_DEBUG: "true"
      WP_DEBUG_DISPLAY: "true"
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 0

volumes:
  db-data: