version: '3.5'

services:
  redis:
    image: redis:5.0.3-alpine
    volumes:
      - redis_data:/var/lib/redis
    ports:
      - "6380:6379"
    logging:
      driver: none

  wordpress_db:
    image: bianjp/mariadb-alpine
    volumes:
      - "db-data:/var/lib/mysql"
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    logging:
      driver: none

  wordpress:
    build:
      context: ../../..
      dockerfile: Dockerfile
    depends_on:
      - redis
      - wordpress_db
    volumes:
      - "../../../wp-content:/var/www/wp-content"
    ports:
      - "8080:80"
    environment:
      IS_DOCKER: "true"
      APP_ENV: development
      NODE_ENV: development
      DB_HOST: wordpress_db
      DB_PASSWORD: wordpress
      DB_NAME: wordpress
      DB_USER: wordpress
      WORDPRESS_SITE_URL: http://www.dev.secretparty.io:8080
      FS_METHOD: direct
      WP_REDIS_HOST: redis
      WP_REDIS_DATABASE: 4
      # For debugging only:
      WP_DEBUG: "true"
      WP_DEBUG_DISPLAY: "true"

volumes:
  db-data: